### ISSUE TITLE
设备掉线

### ISSUE THREAD

**Issue by KDWYZ** [Samuel-0-0/phicomm_dc1-esphome#1]
模块型号：csm64f02
固件：dc1_homeassistant  
路由器：斐讯k2p A2  官改固件
固件编译环境：win10  1803

问题描述： 
     未接入HA平台状态下， wifi指示灯一直闪烁，连接上wifi后还是闪烁，并且连接上wifi之后路由器后台在线设备列表里没有DC1插排，300S后自动重启。
     定时重启能关闭，但是WIFI-LED灯光一直闪烁，路由器后台不显示是怎么回事呢，请问固件就是这么设计的，接入HA平台才算在线，其他状态算离线，还是bug，或者是操作不对？

**Comment by Samuel-0-0** [comment]
在api和wifi下修改为reboot_timeout: 0s，没有的话自己增加
