### ISSUE TITLE
建议：插座名称根据wifi MAC地址后几位自动生成

### ISSUE THREAD

**Issue by zsq19958629** [Samuel-0-0/phicomm_dc1-esphome#11]
yaml配置文件里边只用填写插座名称的头部，比如我的是dc1，最终编译后的设备名称大概为dc1_AABBCCDD，这里的AABBCCDD是mac地址后六位。这样，配置最终配置文件比较通用。
我家里有8个dc1插座，需要维护的配置文件就有8个

**Comment by Samuel-0-0** [comment]
伪需求
