### ISSUE TITLE
作者有无研究过原厂ota方式？

### ISSUE THREAD

**Issue by hclsl1** [Samuel-0-0/phicomm_dc1-esphome#14]
如果能用dns劫持方式劫持到自己的服务器，使用原厂ota方式升级，那就避免了拆外壳等一系列动作，省事多了。我尝试了将原厂bin升级到一块nodemcu中，想看下串口信息，试了几个常用波特率，全是乱码，感觉串口在不停输出。
不知道有人抓过原厂ota或者了解这个串口调试的人是否可以贡献点信息，如果能破解原厂ota，那后续升级就好办多了

**Comment by wanghuangjie** [comment]
> 如果能用dns劫持方式劫持到自己的服务器，使用原厂ota方式升级，那就避免了拆外壳等一系列动作，省事多了。我尝试了将原厂bin升级到一块nodemcu中，想看下串口信息，试了几个常用波特率，全是乱码，感觉串口在不停输出。
> 不知道有人抓过原厂ota或者了解这个串口调试的人是否可以贡献点信息，如果能破解原厂ota，那后续升级就好办多了

方便提供原厂的bin文件我研究下嘛？
我的邮箱是1024py@gmail.com

**Comment by Samuel-0-0** [comment]
原厂OTA是由服务器发起，设备收到信息后下载升级，服务器已挂，已经无法验证具体的OTA方式

**Comment by wanghuangjie** [comment]
1M的那个bin文件在不带b的芯片上成功恢复
2M的那个bin文件，始终不能恢复原厂固件。

flash vendor:
A1h : FM
flash devID:
4014h
QUAD;8Mbit
crystal:
26 Mhz

**Comment by hclsl1** [comment]
@wanghuangjie 不带b芯片啥意思？能看到串口打印信息吗

**Comment by wanghuangjie** [comment]
> @wanghuangjie 不带b芯片啥意思？能看到串口打印信息吗

分两种芯片。具体见该项目的readme。

另外，我长期在用的3台dc1，经常性的丢固件。
现在都刷回原厂，通过劫持的方式去运作了。

我手上的，不管带不带b，用1M的去恢复就可以了。

`esptool.py  --port /dev/tty.usbserial-A9M9DV3R -b 115200 write_flash --flash_size 1MB 0x0 /Users/wanghuangjie/Desktop/dc1_original_1M.bin  `

**Comment by Samuel-0-0** [comment]
> 1M的那个bin文件在不带b的芯片上成功恢复
> 2M的那个bin文件，始终不能恢复原厂固件。
> 
> flash vendor:
> A1h : FM
> flash devID:
> 4014h
> QUAD;8Mbit
> crystal:
> 26 Mhz

带不带b只是针对flash大小，1m的固件可以写到2m的上面正常使用，反过来不行
