### ISSUE TITLE
输入中文后WebServer显示错乱

### ISSUE THREAD

**Issue by KDWYZ** [Samuel-0-0/phicomm_dc1-esphome#2]
`sensor:
  - platform: cse7766
    voltage:
      name: "${device_name} 电压"
    current:
      name: "${device_name} 电流"
    power:
      name: "${device_name} 功率"`

将name的值改为中文后，WebServer中name对应的state对应不上，比如：uptime的state变成了239V

**Comment by Samuel-0-0** [comment]
WebServer本身就存在问题
