### ISSUE TITLE
使用ch341a TTL刷机，Mac系统，但是无法线刷，会报错。

### ISSUE THREAD

**Issue by iYongHsu** [Samuel-0-0/phicomm_dc1-esphome#5]
![image](https://user-images.githubusercontent.com/28946326/56233942-cfe95300-60b6-11e9-94a2-17b3344bca67.png)

**Comment by summmer121** [comment]
同ch341a TTL刷机，免搭建环境版，报错一样

**Comment by iYongHsu** [comment]
> 同ch341a TTL刷机，免搭建环境版，报错一样

后来使用Windows的免搭建环境版，已经发现问题了，ch341a 还是连接编程器自带的5V电源吧，外接电源无法识别，会连接超时。

**Comment by summmer121** [comment]
我连接的就是编程器自带的5v  有联系方式吗  我想加你咨询下  给你看下我的接线图

**Comment by iYongHsu** [comment]
> 我连接的就是编程器自带的5v 有联系方式吗 我想加你咨询下 给你看下我的接线图

有先短接进入UART再插电源吗？

**Comment by summmer121** [comment]
谢谢你的帮助 问题解决了  是ch341驱动的问题  换了朋友ch340的板子 刷好了

**Comment by Samuel-0-0** [comment]
没有驱动到TTL直接跳到OTA模式了
