### ISSUE TITLE
使用OTA上传失败

### ISSUE THREAD

**Issue by tarontop** [Samuel-0-0/phicomm_dc1-esphome#8]
之前按照教程先用线刷刷好了固件并接入了homeassistant，然后我就想试试OTA看能不能上传，结果到最后报错，看报错内容像是没有响应，但是它返回了具体的IP地址了应该连上了，还有就是默认设置了OTA密码但是在OTA上传过程中没有用到，请问大佬这是什么原因。
![QQ截图20190608204644](https://user-images.githubusercontent.com/37043404/59147596-427c0c80-8a30-11e9-9895-4f9b5a439606.png)
![QQ截图20190608205152](https://user-images.githubusercontent.com/37043404/59147597-4314a300-8a30-11e9-9944-059813ba83bf.png)

**Comment by Samuel-0-0** [comment]
关于OTA失败的问题是官方就存在的，具体请看ESPHOME关于OTA的描述

**Comment by mybays** [comment]
我猜你可能是1MB的模块,使用了2MB的配置,这样的话是升级不了的.
换成1MB的配置可能能解决问题.
